name: Publish to extension store

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Make zip file
        run: zip -r ClintonCAT.zip *

      - name: Upload archive as artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ClintonCAT.zip
          path: ClintonCAT.zip

  firefox_publish:
    runs-on: ubuntu-latest
    needs: create_zip
    steps:
    - name: Download prepared archive
      uses: actions/download-artifact@v4.1.8
      with:
        name: ClintonCAT.zip
    
    - uses: wdzeng/firefox-addon@v1
      with:
        addon-guid: "{a7dd0cb9-76e3-4c95-9abb-ece5fd1351fe}"
        xpi-path: ClintonCAT.zip
        self-hosted: false
        license: MIT
        approval-notes: "The extension source can be found at https://github.com/WayneKeenan/ClintonCAT"
        jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
        jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
