name: Publish to extension store

on:
  release:
    types: [published]
    
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout release source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3
